version: "3.8"

services:
  web:
    build: .
    ports:
      - "8004:8000"
    container_name: fastapi_app
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    depends_on:
      - db
      - redis
    networks:
      - app_net

  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:

